/**
 * ITR-PLA-001 PDF orchestrator.
 * Primary: HTML + Puppeteer. No fallback — throws on failure.
 */

import type { SectionInfo } from "./types";
import type { RecordRow } from "./mapper";
import { generateITRPla001PdfHTML } from "./itr-pla-001-puppeteer";

export type GenerateResult = {
  buffer: Buffer;
  contentType: string;
  fileName: string;
  source: "puppeteer" | "react-pdf";
};

/**
 * Generate ITR-PLA-001 PDF. Primary: Puppeteer HTML only. Throws on failure.
 */
export async function generateITRPla001PdfWithFallback(
  section: SectionInfo,
  records: RecordRow[],
  pageNumber: number,
  totalPages: number,
  options?: { isOpenITR?: boolean }
): Promise<GenerateResult> {
  console.log("[ITR] generate-with-fallback: RENDERER SELECTED = puppeteer-html");
  console.log("[ITR-PLA-001] input data summary:", {
    sectionName: section?.name,
    recordsCount: records?.length,
    pageNumber,
    totalPages,
    isOpenITR: options?.isOpenITR,
  });

  try {
    const result = await generateITRPla001PdfHTML(
      section,
      records,
      pageNumber,
      totalPages,
      options
    );
    console.log("[ITR-PLA-001] successful PDF buffer size:", result.buffer?.length ?? 0);
    console.log("[ITR] FILE GENERATED BY: puppeteer-html");
    return { ...result, source: "puppeteer" };
  } catch (err) {
    const e = err as Error;
    const msg = e?.message ?? String(err);
    console.error("[ITR] primary renderer failed: puppeteer-html");
    console.error("[ITR] error.message:", msg);
    console.error("[ITR] error.stack:", e?.stack ?? "(no stack)");
    if (e?.cause) console.error("[ITR] error.cause:", e.cause);
    throw new Error(`Puppeteer rendering failed for ITR-PLA-001: ${msg}`);
  }
}
