/**
 * ITR-PLA-001 PDF orchestrator.
 * Primary: HTML + Puppeteer. Fallback: React-PDF.
 */

import type { SectionInfo } from "./types";
import type { RecordRow } from "./mapper";
import { generateITRPla001PdfHTML } from "./itr-pla-001-puppeteer";
import { generateITRPla001PdfReact } from "./itr-pla-001-react-pdf";

export type GenerateResult = {
  buffer: Buffer;
  contentType: string;
  fileName: string;
  source: "puppeteer" | "react-pdf";
};

/**
 * Generate ITR-PLA-001 PDF. Primary: Puppeteer HTML. Fallback: React-PDF.
 */
export async function generateITRPla001PdfWithFallback(
  section: SectionInfo,
  records: RecordRow[],
  pageNumber: number,
  totalPages: number,
  options?: { isOpenITR?: boolean }
): Promise<GenerateResult> {
  console.log("[ITR] generate-with-fallback: RENDERER SELECTED = puppeteer-html");
  console.log("[ITR-PLA-001] input data summary:", {
    sectionName: section?.name,
    recordsCount: records?.length,
    pageNumber,
    totalPages,
    isOpenITR: options?.isOpenITR,
  });

  try {
    const result = await generateITRPla001PdfHTML(
      section,
      records,
      pageNumber,
      totalPages,
      options
    );
    console.log("[ITR-PLA-001] successful PDF buffer size:", result.buffer?.length ?? 0);
    console.log("[ITR] FILE GENERATED BY: puppeteer-html");
    return { ...result, source: "puppeteer" };
  } catch (err) {
    const e = err as Error;
    console.error("[ITR] primary renderer failed: puppeteer-html");
    console.error("[ITR] error.message:", e?.message ?? String(err));
    console.error("[ITR] error.stack:", e?.stack ?? "(no stack)");
    if (e?.cause) console.error("[ITR] error.cause:", e.cause);

    const noFallback = process.env.ITR_DISABLE_REACT_PDF_FALLBACK === "true";
    if (noFallback) {
      console.error("[ITR] ITR_DISABLE_REACT_PDF_FALLBACK=true → rethrowing (no fallback)");
      throw err;
    }

    console.log("[ITR] fallback renderer selected: react-pdf");
    const result = await generateITRPla001PdfReact(
      section,
      records,
      pageNumber,
      totalPages,
      options
    );
    console.log("[ITR-PLA-001] fallback PDF buffer size:", result.buffer?.length ?? 0);
    return { ...result, source: "react-pdf" };
  }
}
